services:
  postgres:
    image: 'postgres:latest'
    environment:
      POSTGRES_DB: skillguest-db
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - 5433:5432
  zookeeper:
    image: confluentinc/cp-zookeeper:6.2.0
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:6.2.0
    ports:
      - 9092:9092
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

  interview:
    build: TechnicalAdvisorService
    mem_limit: 350m
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  notification:
    build: Notificationservice
    mem_limit: 350m
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  technicaladvisor:
    build: TechnicalAdvisorservice
    mem_limit: 350m
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  api:
    build: api
    mem_limit: 350m
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
